# Generated by Django 5.2.4 on 2025-07-17 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="video",
            old_name="uploaded_at",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="video",
            name="email",
        ),
        migrations.AddField(
            model_name="video",
            name="title",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="video",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="videos",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="video",
            name="status",
            field=models.CharField(default="pending", max_length=50),
        ),
    ]
